### ISSUE TITLE
"export default" syntax for main package export breaks non-es2015 consumers

### ISSUE THREAD

**Issue by euwest** [yola/pixabayjs#40]
[:sadpanda:](http://stackoverflow.com/questions/33704714/cant-require-default-export-value-in-babel-6-x/33705077#33705077)

**tl;dr:** `export default <thing>` transpiles into a module that, when importing via commonJS(i.e. in a node environment), means you have to `var thing = require('thing').default();`

**Comment by LionOps** [comment]
If it's important, we can use https://babeljs.io/docs/plugins/transform-es2015-modules-commonjs/
